Adding unit test coverage check

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -15,5 +15,17 @@ jobs:
           go-version: 1.18
           cache: true
 
-      - name: build application
+      - name: Build application using Make
         run: make build
+
+      - name: Unit Test Coverage Check
+        run: |
+              echo "Threshold is set at: 80 %"
+              cov=`go tool cover -func=coverage.out | tail -1 | cut -d'     ' -f 11 | cut -d'%' -f1`
+              echo "Current coverage : $cov %"
+              if (( 80 > cov)); then
+                  echo "OK"
+              else
+                  echo "Failed"
+                  exit 1
+              fi
