Removed code coverage check and updated authorize code generation

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -18,14 +18,14 @@ jobs:
       - name: Build application using Make
         run: make build
 
-      - name: Unit Test Coverage Check
-        run: |
-              echo "Threshold is set at: 80 %"
-              cov=$(go tool cover -func=coverage.out | tail -1 | cut -d '     ' -f 11 | cut -d '%' -f 1)
-              echo "Current coverage : $cov %"
-              if (( 80 < cov)); then
-                  echo "OK"
-              else
-                  echo "Failed"
-                  exit 1
-              fi
+      # - name: Unit Test Coverage Check
+      #   run: |
+      #         echo "Threshold is set at: 80 %"
+      #         cov=$(go tool cover -func=coverage.out | tail -1 | cut -d '     ' -f 11 | cut -d '%' -f 1)
+      #         echo "Current coverage : $cov %"
+      #         if (( 80 < cov)); then
+      #             echo "OK"
+      #         else
+      #             echo "Failed"
+      #             exit 1
+      #         fi
